/*----------------------------------------------------------------------------/
/  SD Card function implementation				                              /
/-----------------------------------------------------------------------------/
/
/ Functions to create, open and write to files on a FAT32 formatted SD Card.
/
/----------------------------------------------------------------------------*/

#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include "ff.h"
#include "SDCard.h"

FSIZE_t offset;	//File offset

volatile UINT Timer;	//Performance timer (100Hz increment)

//100Hz timer interrupt generated by OC0A

ISR(TIMER0_COMPA_vect)
{
	Timer++;			//Performance counter for this module
	mmc_disk_timerproc();	//Drive timer procedure of low level disk I/O module
}

void Start_Timer_SD()
{
	//Start 100Hz system timer with TC0
	OCR0A = F_CPU / 1024 / 100 - 1;
	TCCR0A |= (1<<WGM01);	//Set timer to CTC
	TCCR0B |= (1 << CS01) | (1 << CS00); //Set prescaler to 1024
	TIMSK0 |= (1 << OCIE0A);    //Set the ISR COMPA vect
	
	sei();	//Enable interrupts
}


void Stop_Timer_SD()
{
	//Start 100Hz system timer with TC0
	//OCR0A = F_CPU / 1024 / 100 - 1;
	TCCR0A &= !(1<<WGM01);	//Set timer to CTC
	TCCR0B &= !(1 << CS01) | (1 << CS00); //Set prescaler to 1024
	TIMSK0 &= !(1 << OCIE0A);    //Set the ISR COMPA vect
	
	cli();	//Disable interrupts
}


uint8_t File_Exists(char *File_Name, FATFS *FatFs)
{
	FILINFO finfo;
	FRESULT fr;
	
	f_mount(FatFs, "", 1);
	
	fr = f_stat(File_Name, &finfo);	//Check if file exists
	
	f_mount(0, "", 0);
	
	return fr;
}

uint8_t Delete_File(char *File_Name, FATFS *FatFs)
{
	FILINFO finfo;
	FRESULT fr;
	
	f_mount(FatFs, "", 1);
	fr = f_stat(File_Name, &finfo);	//Check if file exists
	
	if(fr == FR_OK)
	{
		fr = f_unlink(File_Name);
		f_mount(0, "", 0);
		_delay_ms(250);
		return fr;
	}
	else
	{
		f_mount(0, "", 0);
		return 1;		
	}		
}

uint8_t Create_File(char *File_Name, FATFS *FatFs)
{
	FRESULT fr;
	FIL fil;
			
	f_mount(FatFs, "", 1);

	fr = f_open(&fil, File_Name, FA_WRITE | FA_CREATE_ALWAYS);
		
	f_close(&fil);	
		
	f_mount(0, "", 1);

	return fr;
}

uint8_t Write_File(char *File_Name, FATFS *FatFs, char *data, uint8_t bytes)
{
	FIL fil;        
	FRESULT fr; 
	FILINFO finfo;
	char buffer[32];
	int bytes_written = 0;
	
	f_mount(FatFs, "", 1);
	
	fr = f_stat(File_Name, &finfo);	//Check if file exists
	if(fr != FR_OK)
	{
		return fr;
	}

	fr = f_open(&fil, File_Name, FA_WRITE | FA_OPEN_APPEND);
	if(fr != FR_OK)
	{
		return fr;
	}

	memset(buffer, 0, sizeof(buffer));

	strcpy(buffer, data);

	fr = f_write(&fil, (const void*)buffer, strlen(buffer), &bytes_written);
	if(fr != FR_OK)
	{
		f_close(&fil);
		f_mount(0, "", 0);
		return fr;
	}

	f_sync(&fil);

	f_close(&fil);
	
	f_mount(0, "", 0);
	
	return 0;
}

uint8_t Open_File(char *File_Name, FATFS *FatFs, FIL *file_object)
{
	FIL fil;
	FRESULT fr;
	FILINFO finfo;
	char buffer[32];
	int bytes_written = 0;
	
	f_mount(FatFs, "", 1);

	fr = f_stat(File_Name, &finfo);	//Check if file exists
	if(fr != FR_OK)
	{
		return fr;
	}
	
	fr = f_open(&fil, File_Name, FA_WRITE | FA_OPEN_APPEND);
	if(fr != FR_OK)
	{
		return fr;
	}
	
	*file_object = fil;
	
	return 0;
}

uint8_t Write_File_2(char *File_Name, FATFS *FatFs, char *data, uint8_t bytes)
{
	FIL fil;
	FRESULT fr;
	FILINFO finfo;
	char buffer[32];
	int bytes_written = 0;
	
	f_mount(FatFs, "", 1);

	fr = f_stat(File_Name, &finfo);	//Check if file exists
	if(fr != FR_OK)
	{
		return fr;
	}
	
	fr = f_open(&fil, File_Name, FA_WRITE | FA_OPEN_APPEND);
	if(fr != FR_OK)
	{
		return fr;
	}
	
	memset(buffer, 0, sizeof(buffer));

	strcpy(buffer, data);
	
	fr = f_write(&fil, (const void*)buffer, strlen(buffer), &bytes_written);
	if(fr != FR_OK)
	{
		f_close(&fil);
		f_mount(0, "", 0);
		return fr;
	}

	f_sync(&fil);

	f_close(&fil);
	
	f_mount(0, "", 0);
	
	return 0;
}

uint8_t Close_File(char *File_Name, FATFS *FatFs, FIL *file_object)
{
	FIL fil = *file_object;

	f_sync(&fil);

	f_close(&fil);
	
	f_mount(0, "", 0);
	
	return 0;
}



//SPI Functions

void SPI_MasterInit(void)
{
	//Set MOSI and SCK output, all others input
	DDRB = (1<<PB3)|(1<<PB5);
	//Enable SPI, Master, set clock rate fck/16
	SPCR = (1<<SPE)|(1<<MSTR)|(1<<SPR0);
}
